### ISSUE TITLE
Can't run `rake pull_wiki` task: cannot load such file -- spider/lib/spider.rb

### ISSUE THREAD

**Issue by datapolitan** [darwin/move-wiki#1]
Getting the following error when try to run rake pull_wiki task:

```
rake aborted!
cannot load such file -- spider/lib/spider.rb
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/richarddunks/Dropbox/Datapolitan/github/move-wiki/rakefile:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/rake_module.rb:25:in `load'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/rake_module.rb:25:in `load_rakefile'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:604:in `raw_load_rakefile'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:89:in `block in load_rakefile'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:160:in `standard_exception_handling'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:88:in `load_rakefile'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:72:in `block in run'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:160:in `standard_exception_handling'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:70:in `run'
/usr/bin/rake:37:in `<main>'
```

Changed the permissions on the files (`chmod 777 spider/lib/spider.rb`) and can open the file in a text editor but still doesn't seem accessible in the app.

**Comment by StanBoyet** [comment]
+1

**Comment by ghost** [comment]
Same problem here.

I managed to find this post: http://www.backtrack-linux.org/forums/showthread.php?t=41807 but am unsuccessful at getting the steps in the second to last post to work.

I changed my environment for Ruby from 2.0 to ree-1.8.7-2011.03 and then ree-1.8.7-2012.02 using [rbyenv](https://github.com/sstephenson/rbenv) and [ruby-build](https://github.com/sstephenson/ruby-build), but while I try to install the spider gem in those environments I get a segfault: 11.

**Comment by allenwlee** [comment]
+1 same problem

**Comment by smrgeoinfo** [comment]
+1 same problem. Running Ruby 3.0.0, Windows 10
